# Site settings
title: "Felix Komoll"
email: "radiosansibar@gmail.com"
description: > # Felix Komoll, Gitarrist, Berlin Germany, Transkription, Bela Bartok, Sergei Prokofjew
baseurl: "/felixkomoll/" # the subpath of your site, e.g. /blog/
url: "http://www.radiosansibar.de" # the base hostname & protocol for your site

# User setting
owner: "Felix Komoll"
email: "radiosansibar@gmail.com"
facebook_username: "thommy2000thaler"
#twitter_username:
#github_username:
#address:
#  - line:
#  - line:
  # Feel free to add more lines here
telephone: +49 179 2073245
copyright: Thaler Promotions

# API settings
#google_api_key:

# Build settings
markdown: kramdown
